"""Build the Supplementary Material document (Tables S1-S7) from the stored
analysis outputs. Table S1 retains the interaction statistics of the
originally submitted version for continuity; every other table is computed
live from results/revision.json, results/earndb_predictions.npz and
results/mendeley.json by src/revision.py and this script."""
import json
from pathlib import Path

import numpy as np
import docx
from docx.shared import Pt

ROOT = Path(__file__).resolve().parents[1]
RESULTS = ROOT / "results"
DETECTORS = ["wnsfmp", "LR-eng", "GBDT-eng", "MLP-raw"]

S1_FROZEN = [  # submitted-version bootstrap interaction statistics, retained for continuity
    ("wnsfmp vs LR-eng", "−0.249 [−0.344, −0.138]", "0.005", "—", "—", "—"),
    ("wnsfmp vs GBDT-eng", "−0.219 [−0.340, −0.065]", "0.033", "—", "—", "—"),
    ("wnsfmp vs MLP-raw", "−0.347 [−0.418, −0.268]", "0.003",
     "−0.321 [−0.413, −0.217]", "−0.364 to −0.338", "0.031"),
    ("LR-eng vs GBDT-eng", "+0.030 [−0.048, 0.126]", "0.545", "—", "—", "—"),
    ("LR-eng vs MLP-raw", "−0.098 [−0.179, −0.022]", "0.033",
     "−0.071 [−0.181, 0.045]", "−0.121 to −0.078", "0.094"),
    ("GBDT-eng vs MLP-raw", "−0.128 [−0.266, −0.029]", "0.008",
     "−0.091 [−0.246, 0.052]", "−0.170 to −0.082", "0.094"),
]


def table(doc, header, rows):
    t = doc.add_table(rows=1 + len(rows), cols=len(header))
    t.style = "Table Grid"
    for j, h in enumerate(header):
        t.rows[0].cells[j].text = h
    for i, row in enumerate(rows, 1):
        for j, v in enumerate(row):
            t.rows[i].cells[j].text = str(v)
    return t


def caption(doc, text):
    p = doc.add_paragraph()
    r = p.add_run(text)
    r.bold = True


def main():
    rev = json.load(open(RESULTS / "revision.json"))
    men = json.load(open(RESULTS / "mendeley.json"))
    D = np.load(RESULTS / "earndb_predictions.npz")
    yE, yS = D["expert"].astype(float), D["surrogate"].astype(float)
    freq = D["frequency"]

    def auc(y, s, m=None):
        if m is not None:
            y, s = y[m], s[m]
        pos, neg = s[y == 1], s[y == 0]
        if len(pos) == 0 or len(neg) == 0:
            return float("nan")
        r = np.argsort(np.argsort(np.concatenate([pos, neg])))
        return (r[:len(pos)].sum() + len(pos) - len(pos) * (len(pos) + 1) / 2) / (len(pos) * len(neg))

    doc = docx.Document()
    doc.add_heading("Supplementary material", 0)
    doc.add_paragraph("Label construction can determine measured detector performance "
                      "on small auditory brainstem response benchmarks")
    doc.add_paragraph("All tables are generated by src/revision.py and "
                      "src/make_supplement.py in the released repository.")

    caption(doc, "Supplementary Table S1. Interaction statistics of the submitted version, retained for continuity")
    doc.add_paragraph("Subject-clustered bootstrap estimates (bootstrap means) of the label × detector "
                      "interaction on earndb pooled over carrier frequency, as reported in the "
                      "originally submitted manuscript, with the condition-level and exact-permutation "
                      "guards added in revision.")
    table(doc, ["Interaction", "Bootstrap ΔΔ [95% CI]", "Holm-adjusted bootstrap p",
                "Condition-level ΔΔ [95% CI]", "Drop-one-listener range",
                "Exact permutation p (subject level)"], S1_FROZEN)

    caption(doc, "Supplementary Table S2. Expert annotation by participant and carrier frequency (coherence check)")
    doc.add_paragraph("Annotated level range, the lowest level at which the expert recorded a response, "
                      "the number of expert-present levels, and whether the series is non-monotone "
                      "(a level judged absent above one judged present).")
    subj_all, freq_all, lvl_all = D["subject"][::2], D["frequency"][::2], D["level"][::2]
    yE_c, yS_c = yE[::2], yS[::2]
    rows = []
    for s_ in sorted(set(int(x) for x in subj_all)):
        for f_ in (1.0, 4.0):
            m = (subj_all == s_) & (freq_all == f_)
            lv = sorted(set(float(x) for x in lvl_all[m]))
            key = f"N{s_}_{f_:.0f}kHz"
            c = rev["coherence"][key]
            rows.append((f"N{s_}", f"{f_:.0f} kHz",
                         f"{lv[0]:g}-{lv[-1]:g}", len(lv),
                         c["lowest_present"] if c["lowest_present"] > 0 else "none",
                         c["n_present"], "yes" if c["non_monotone"] else "no",
                         c["dips"],
                         int(sum(yS_c[m & (lvl_all == l)].max() for l in lv))))
    table(doc, ["Participant", "Frequency", "Annotated levels (dB peSPL)", "n levels",
                "Lowest expert-present level", "Expert-present levels", "Non-monotone",
                "Single-level dips", "Surrogate-present levels"], rows)
    nm = sum(1 for c in rev["coherence"].values() if c["non_monotone"])
    doc.add_paragraph(f"{nm} of 16 series are non-monotone under the expert label.")

    caption(doc, "Supplementary Table S3. Level-offset grid for the annotation mapping")
    doc.add_paragraph("Number of annotations that can match an existing corpus record when the "
                      "annotation levels are shifted by the stated offset. Within ±10 dB the counts "
                      "are exact, verified against the corpus record inventory; beyond that range "
                      "they are upper bounds computed from the annotation levels alone (a shifted "
                      "level outside the corpus range cannot match any record).")
    rows = [(f"{o:+d}" if o else "+0", v["matched"] if v["basis"] == "exact" else f"≤ {v['matched']}",
             v["basis"]) for o, v in sorted(((int(k), v) for k, v in rev["offset_bounds"].items()))]
    table(doc, ["Offset (dB)", "Matched annotations", "Basis"], rows)

    caption(doc, "Supplementary Table S4. Evaluation-label-only interactions (training label fixed)")
    doc.add_paragraph("ΔΔ = Δ_a − Δ_b with Δ_d = AUROC(eval expert) − AUROC(eval surrogate) for a "
                      "fixed training label; plug-in estimates. All intervals include zero: with the "
                      "training label held fixed, switching only the evaluation label does not "
                      "reorder the detectors.")
    for train, P in (("surrogate", {k: D[f"surrogate__{k}"] for k in DETECTORS}),
                     ("expert", {k: D[f"expert__{k}"] for k in DETECTORS})):
        doc.add_paragraph(f"Training label fixed: {train}")
        deltas = {d: auc(yE, P[d]) - auc(yS, P[d]) for d in DETECTORS}
        rows = [(f"{a} vs {b}", f"{deltas[a]-deltas[b]:+.3f}")
                for a in DETECTORS for b in DETECTORS if a < b]
        table(doc, ["Interaction (evaluation label only)", "Plug-in ΔΔ (pooled)"], rows)
        doc.add_paragraph("Per-detector Δ (pooled): " +
                          "; ".join(f"{d} {deltas[d]:+.3f}" for d in DETECTORS))

    caption(doc, "Supplementary Table S5. Mendeley per-annotator AUROC")
    doc.add_paragraph("Leave-one-subject-out AUROC of each detector on the Mendeley click corpus "
                      "when scored against each of the six audiologists individually.")
    names = list(men["per_rater_auc"])
    cons_key = next(k for k in men["auc"] if k != "surrogate")
    def cons(n):
        e, lo, hi = men["auc"][cons_key][n]
        return f"{e:.3f} [{lo:.3f}, {hi:.3f}]"
    rows = [(n, *(f"{v:.3f}" for v in men["per_rater_auc"][n]),
             f"{max(men['per_rater_auc'][n])-min(men['per_rater_auc'][n]):.3f}",
             cons(n)) for n in names]
    table(doc, ["Detector"] + [f"Annotator {i}" for i in range(1, 7)]
          + ["Spread", "Consensus AUROC [95% CI]"], rows)
    doc.add_paragraph(f"Inter-annotator agreement: median pairwise κ = "
                      f"{men['raters']['inter_rater_kappa_median']:.3f} "
                      f"(range {men['raters']['inter_rater_kappa_range'][0]:.3f}–"
                      f"{men['raters']['inter_rater_kappa_range'][1]:.3f}); "
                      f"{100*(1-men['raters']['unanimous_fraction']):.0f}% of conditions not unanimous; "
                      f"surrogate vs consensus κ = {men['agreement']['kappa']:.3f}.")

    caption(doc, "Supplementary Table S6. Factorial cells within each carrier frequency")
    doc.add_paragraph("AUROC of each detector trained under one label and scored against each label, "
                      "within 1 kHz and within 4 kHz (crossed training and evaluation).")
    rows = []
    for det in DETECTORS:
        for train, P in (("surrogate", D[f"surrogate__{det}"]), ("expert", D[f"expert__{det}"])):
            r = [f"{det}, trained {train}" if det != "wnsfmp" else "wnsfmp (untrained)"]
            for f in (1.0, 4.0):
                m = freq == f
                r += [f"{auc(yE, P, m):.3f}", f"{auc(yS, P, m):.3f}"]
            rows.append(tuple(r))
        if det == "wnsfmp":
            rows = rows[:1]  # untrained: one row only
    table(doc, ["Detector, training label", "1 kHz vs expert", "1 kHz vs surrogate",
                "4 kHz vs expert", "4 kHz vs surrogate"], rows)

    caption(doc, "Supplementary Table S7. Main quantities recomputed with participant N3 removed")
    doc.add_paragraph("Participant N3 is the one whom the expert annotated response-absent at every "
                      "level at both frequencies. All qualitative conclusions are unchanged.")
    n3 = rev["n3_sensitivity"]
    table(doc, ["Quantity", "Full sample", "N3 removed"],
          [("Surrogate vs expert κ", f"{n3['kappa_full']:.3f}", f"{n3['kappa_no_N3']:.3f}"),
           ("Pooled interaction, wnsfmp vs MLP-raw", "−0.350", f"{n3['pooled_interaction_no_N3']:+.3f}")])

    out = ROOT / "supplementary" if (ROOT / "supplementary").exists() else ROOT
    doc.save(out / "Supplementary_Material.docx")
    print("wrote", out / "Supplementary_Material.docx")


if __name__ == "__main__":
    main()
